- name: Download Android Studio version  .tar.gz package
  get_url:
    url: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.22/android-studio-2021.1.1.22-linux.tar.gz
    checksum: "sha256:a9a5eaffe1873c684b99786db482d3b11fcbc003a773634f8e740c7bca148539"
    dest: "{{ download_cache_dir }}/androidstudio.tar.gz"
    force: no

#- name: Install 64bit libraries
#  apt:
#    name: 
#      - libc6:i386
#      - libncurses5:i386
#      - libstdc++6:i386
#      - lib32z1
#      - libbz2-1.0:i386
#    state: present
#  become: yes

- name: Unzip Android Studio
  unarchive:
    src: "{{ download_cache_dir }}/androidstudio.tar.gz"
    dest: "/usr/local/"

# Does not work due to missing graphics.enviroment. it may not be possible this way.
# https://developer.android.com/studio/install#64bit-libs
- name: Execute stdio.sh
  command: 
    cmd: sh /usr/local/android-studio/bin/studio.sh
  ignore_errors: yes

# Todo install adb

# Issue Device is not reconized:
# https://stackoverflow.com/a/53887437/8301375

